"""0001_initial_schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-04-23 18:44:19.689127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.types import BigInteger


@compiles(BigInteger, "sqlite")
def _compile_bigint_sqlite(_type, _compiler, **_kw):
    # SQLite 只有 INTEGER PRIMARY KEY 才能稳定自增；
    # 将 BIGINT 统一映射为 INTEGER 以保证本地初始化链可执行。
    return "INTEGER"


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_region',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('pinyin', sa.String(length=128), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('parent_code', sa.String(length=12), nullable=True),
    sa.Column('full_path', sa.String(length=256), nullable=True),
    sa.Column('province_code', sa.String(length=12), nullable=True),
    sa.Column('city_code', sa.String(length=12), nullable=True),
    sa.Column('district_code', sa.String(length=12), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('center_address', sa.String(length=256), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('admin_region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_region_parent_code'), ['parent_code'], unique=False)

    op.create_table('audit_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_no', sa.String(length=32), nullable=False),
    sa.Column('biz_type_code', sa.String(length=64), nullable=False),
    sa.Column('biz_id', sa.BigInteger(), nullable=False),
    sa.Column('biz_code', sa.String(length=64), nullable=True),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True),
    sa.Column('current_handler_id', sa.BigInteger(), nullable=True),
    sa.Column('audit_status', sa.String(length=32), nullable=False),
    sa.Column('audit_remark', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    with op.batch_alter_table('audit_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_task_biz_id'), ['biz_id'], unique=False)

    op.create_table('cargo_channel_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('incoming_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.Column('formalized_count', sa.Integer(), nullable=False),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cargo_channel_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cargo_channel_daily_source_type_code'), ['source_type_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cargo_channel_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('code_sequence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('biz_code', sa.String(length=64), nullable=False),
    sa.Column('biz_name', sa.String(length=128), nullable=False),
    sa.Column('target_table', sa.String(length=64), nullable=False),
    sa.Column('target_column', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('date_format', sa.String(length=32), nullable=True),
    sa.Column('separator', sa.String(length=8), nullable=True),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.Column('value_length', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('reset_rule', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_code')
    )
    op.create_table('commodity_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('navigation_constraint_point',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('constraint_type_code', sa.String(length=64), nullable=False),
    sa.Column('province_code', sa.String(length=12), nullable=True),
    sa.Column('city_code', sa.String(length=12), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('severity_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('navigation_constraint_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('constraint_point_id', sa.BigInteger(), nullable=False),
    sa.Column('max_tonnage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_allowed_draft_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min_water_depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('under_keel_clearance_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_air_draft_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_beam_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_length_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('allowed_time_window', sa.String(length=256), nullable=True),
    sa.Column('restriction_rule_json', sa.JSON(), nullable=True),
    sa.Column('rule_description', sa.String(length=512), nullable=True),
    sa.Column('warning_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['constraint_point_id'], ['navigation_constraint_point.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constraint_point_id', name='uk_navigation_constraint_profile_point')
    )
    with op.batch_alter_table('navigation_constraint_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_navigation_constraint_profile_constraint_point_id'), ['constraint_point_id'], unique=False)

    op.create_table('region',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('region_type_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('current_boundary_version_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ship_import_batch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_no', sa.String(length=32), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_table('ship_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ais_id', sa.String(length=32), nullable=False),
    sa.Column('ship_name', sa.String(length=128), nullable=False),
    sa.Column('ship_name_en', sa.String(length=256), nullable=True),
    sa.Column('current_mmsi', sa.String(length=16), nullable=True),
    sa.Column('ship_type_code', sa.String(length=64), nullable=False),
    sa.Column('navigation_power_type_code', sa.String(length=64), nullable=False),
    sa.Column('home_port_code', sa.String(length=12), nullable=True),
    sa.Column('home_port_name', sa.String(length=128), nullable=True),
    sa.Column('owner_name', sa.String(length=128), nullable=True),
    sa.Column('profile_status_code', sa.String(length=64), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ais_id')
    )
    op.create_table('stat_cargo_city_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('city_code', sa.String(length=12), nullable=False),
    sa.Column('freight_count', sa.Integer(), nullable=False),
    sa.Column('tonnage', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('loading_count', sa.Integer(), nullable=False),
    sa.Column('unloading_count', sa.Integer(), nullable=False),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_cargo_city_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_cargo_city_daily_city_code'), ['city_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_cargo_city_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('stat_cargo_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_freight_count', sa.Integer(), nullable=False),
    sa.Column('total_tonnage', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_estimated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_cargo_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_cargo_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('stat_cargo_flow_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('origin_city_code', sa.String(length=12), nullable=False),
    sa.Column('destination_city_code', sa.String(length=12), nullable=False),
    sa.Column('freight_count', sa.Integer(), nullable=False),
    sa.Column('tonnage', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_cargo_flow_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_cargo_flow_daily_destination_city_code'), ['destination_city_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_cargo_flow_daily_origin_city_code'), ['origin_city_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_cargo_flow_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('stat_job_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_code', sa.String(length=64), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('scope_desc', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('affected_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_job_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_job_run_job_code'), ['job_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_job_run_stat_date'), ['stat_date'], unique=False)

    op.create_table('stat_ship_city_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('city_code', sa.String(length=12), nullable=False),
    sa.Column('active_ship_count', sa.Integer(), nullable=False),
    sa.Column('total_deadweight_ton', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_ship_city_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_ship_city_daily_city_code'), ['city_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_ship_city_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('stat_ship_flow_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('origin_city_code', sa.String(length=12), nullable=False),
    sa.Column('destination_city_code', sa.String(length=12), nullable=False),
    sa.Column('ship_count', sa.Integer(), nullable=False),
    sa.Column('voyage_count', sa.Integer(), nullable=False),
    sa.Column('total_deadweight_ton', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_ship_flow_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_ship_flow_daily_destination_city_code'), ['destination_city_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_ship_flow_daily_origin_city_code'), ['origin_city_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_ship_flow_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('std_dict',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dict_code', sa.String(length=64), nullable=False),
    sa.Column('dict_name', sa.String(length=128), nullable=False),
    sa.Column('dict_name_en', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_code')
    )
    op.create_table('sys_menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_code', sa.String(length=64), nullable=False),
    sa.Column('menu_name', sa.String(length=128), nullable=False),
    sa.Column('menu_type_code', sa.String(length=64), nullable=False),
    sa.Column('route_path', sa.String(length=256), nullable=True),
    sa.Column('component_path', sa.String(length=256), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible_flag', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_code')
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permission_code', sa.String(length=128), nullable=False),
    sa.Column('permission_name', sa.String(length=128), nullable=False),
    sa.Column('permission_type_code', sa.String(length=64), nullable=False),
    sa.Column('resource_path', sa.String(length=256), nullable=True),
    sa.Column('action_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('mobile_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('system_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('value_type_code', sa.String(length=64), nullable=False),
    sa.Column('config_group_code', sa.String(length=64), nullable=False),
    sa.Column('config_profile_code', sa.String(length=64), server_default=sa.text("'DEFAULT'"), nullable=False),
    sa.Column('sensitive_flag', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('encrypted_flag', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('editable_flag', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('config_status_code', sa.String(length=64), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('last_test_status_code', sa.String(length=64), nullable=True),
    sa.Column('last_test_message', sa.String(length=512), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('admin_region_boundary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_region_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('boundary_source_type_code', sa.String(length=64), nullable=False),
    sa.Column('geometry_json', sa.JSON(), nullable=False),
    sa.Column('center_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('center_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('area_km2', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('imported_by', sa.BigInteger(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_region_id'], ['admin_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_region_boundary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_region_boundary_admin_region_id'), ['admin_region_id'], unique=False)

    op.create_table('audit_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('action_code', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('from_status_code', sa.String(length=64), nullable=True),
    sa.Column('to_status_code', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['audit_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_record_task_id'), ['task_id'], unique=False)

    op.create_table('commodity_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['commodity_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('commodity_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_type_category_id'), ['category_id'], unique=False)

    op.create_table('region_boundary_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('boundary_source_type_code', sa.String(length=64), nullable=False),
    sa.Column('geometry_json', sa.JSON(), nullable=False),
    sa.Column('center_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('center_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('area_km2', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('region_boundary_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_boundary_version_region_id'), ['region_id'], unique=False)

    op.create_table('region_city_relation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('city_region_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type_code', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_region_id'], ['admin_region.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'city_region_id', name='uk_region_city')
    )
    with op.batch_alter_table('region_city_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_city_relation_city_region_id'), ['city_region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_city_relation_region_id'), ['region_id'], unique=False)

    op.create_table('ship_capacity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('deadweight_ton', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reference_load_ton', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_tonnage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_tonnage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('depth_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('design_draft_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('design_speed_kn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hold_count', sa.Integer(), nullable=True),
    sa.Column('capacity_remark', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id')
    )
    op.create_table('ship_certificate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('certificate_type_code', sa.String(length=64), nullable=False),
    sa.Column('certificate_no', sa.String(length=128), nullable=True),
    sa.Column('issuing_authority', sa.String(length=128), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_long_term_valid', sa.Boolean(), nullable=False),
    sa.Column('validity_text_raw', sa.String(length=256), nullable=True),
    sa.Column('verify_status_code', sa.String(length=64), nullable=False),
    sa.Column('structured_payload_json', sa.JSON(), nullable=True),
    sa.Column('source_file_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_certificate_ship_id'), ['ship_id'], unique=False)

    op.create_table('ship_contact',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('contact_role_code', sa.String(length=64), nullable=False),
    sa.Column('mobile_phone', sa.String(length=32), nullable=True),
    sa.Column('wechat', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_contact_ship_id'), ['ship_id'], unique=False)

    op.create_table('ship_dynamic',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('city_code', sa.String(length=12), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('speed_kn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dynamic_status_code', sa.String(length=64), nullable=True),
    sa.Column('last_ais_time', sa.DateTime(), nullable=True),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id')
    )
    op.create_table('ship_import_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('parse_status_code', sa.String(length=64), nullable=False),
    sa.Column('parse_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ship_import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_no', name='uk_ship_import_raw_row')
    )
    with op.batch_alter_table('ship_import_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_import_raw_batch_id'), ['batch_id'], unique=False)

    op.create_table('ship_mmsi_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('mmsi', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id', 'mmsi', 'start_date', name='uk_ship_mmsi_history')
    )
    with op.batch_alter_table('ship_mmsi_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_mmsi_history_ship_id'), ['ship_id'], unique=False)

    op.create_table('ship_name_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('ship_name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_name_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_name_history_ship_id'), ['ship_id'], unique=False)

    op.create_table('ship_operation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('operator_name', sa.String(length=128), nullable=True),
    sa.Column('manager_name', sa.String(length=128), nullable=True),
    sa.Column('main_navigation_area_desc', sa.String(length=256), nullable=True),
    sa.Column('usual_route_desc', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('dispatch_contact_name', sa.String(length=64), nullable=True),
    sa.Column('dispatch_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('risk_level_code', sa.String(length=64), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('ext_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id')
    )
    op.create_table('ship_owner',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=False),
    sa.Column('party_name', sa.String(length=128), nullable=False),
    sa.Column('party_relation_type_code', sa.String(length=64), nullable=False),
    sa.Column('certificate_no', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.String(length=32), nullable=True),
    sa.Column('landline_phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_owner_ship_id'), ['ship_id'], unique=False)

    op.create_table('shipping_route',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('transport_org_type_code', sa.String(length=64), nullable=False),
    sa.Column('multimodal_combination_code', sa.String(length=64), nullable=True),
    sa.Column('origin_region_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_region_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['origin_region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('shipping_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_route_destination_region_id'), ['destination_region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_route_origin_region_id'), ['origin_region_id'], unique=False)

    op.create_table('std_dict_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dict_id', sa.BigInteger(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('item_name_en', sa.String(length=256), nullable=True),
    sa.Column('parent_item_id', sa.BigInteger(), nullable=True),
    sa.Column('item_value', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('ext_json', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dict_id'], ['std_dict.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['std_dict_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_id', 'item_code', name='uk_dict_item')
    )
    with op.batch_alter_table('std_dict_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_std_dict_item_dict_id'), ['dict_id'], unique=False)

    op.create_table('sys_data_scope',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scope_code', sa.String(length=64), nullable=False),
    sa.Column('scope_name', sa.String(length=128), nullable=False),
    sa.Column('data_scope_type_code', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('city_code', sa.String(length=12), nullable=True),
    sa.Column('node_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_code')
    )
    op.create_table('sys_login_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('login_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('login_result_code', sa.String(length=64), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_login_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_login_log_user_id'), ['user_id'], unique=False)

    op.create_table('sys_role_menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id', name='uk_sys_role_menu')
    )
    with op.batch_alter_table('sys_role_menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_role_menu_menu_id'), ['menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_role_menu_role_id'), ['role_id'], unique=False)

    op.create_table('sys_role_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_sys_role_permission')
    )
    with op.batch_alter_table('sys_role_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_role_permission_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_role_permission_role_id'), ['role_id'], unique=False)

    op.create_table('sys_user_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_sys_user_role')
    )
    with op.batch_alter_table('sys_user_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_user_role_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_user_role_user_id'), ['user_id'], unique=False)

    op.create_table('sys_user_status_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status_code', sa.String(length=64), nullable=True),
    sa.Column('to_status_code', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_user_status_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_user_status_log_user_id'), ['user_id'], unique=False)

    op.create_table('transport_node',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('node_type_code', sa.String(length=64), nullable=False),
    sa.Column('province_code', sa.String(length=12), nullable=False),
    sa.Column('city_code', sa.String(length=12), nullable=False),
    sa.Column('district_code', sa.String(length=12), nullable=True),
    sa.Column('city_region_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('lifecycle_status_code', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_hot_node', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_region_id'], ['admin_region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('transport_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_node_city_region_id'), ['city_region_id'], unique=False)

    op.create_table('commodity_standard',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('english_name', sa.String(length=256), nullable=True),
    sa.Column('main_unit', sa.String(length=32), nullable=False),
    sa.Column('density_range_desc', sa.String(length=128), nullable=True),
    sa.Column('dangerous_grade_code', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['commodity_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('commodity_standard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_standard_type_id'), ['type_id'], unique=False)

    op.create_table('node_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_name', sa.String(length=128), nullable=False),
    sa.Column('alias_type_code', sa.String(length=64), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_alias_node_id'), ['node_id'], unique=False)

    op.create_table('ship_certificate_file',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ship_certificate_id', sa.BigInteger(), nullable=True),
    sa.Column('storage_provider_code', sa.String(length=64), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_ext', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_certificate_id'], ['ship_certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_certificate_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_certificate_file_ship_certificate_id'), ['ship_certificate_id'], unique=False)

    op.create_table('ship_import_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_id', sa.BigInteger(), nullable=False),
    sa.Column('ship_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type_code', sa.String(length=64), nullable=False),
    sa.Column('result_code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ship_import_batch.id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['ship_import_raw.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ship_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_import_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_import_record_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_import_record_raw_id'), ['raw_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_import_record_ship_id'), ['ship_id'], unique=False)

    op.create_table('shipping_route_plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('plan_type_code', sa.String(length=64), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_duration_hour', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['shipping_route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_code')
    )
    with op.batch_alter_table('shipping_route_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_route_plan_route_id'), ['route_id'], unique=False)

    op.create_table('sys_role_data_scope',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('data_scope_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_scope_id'], ['sys_data_scope.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'data_scope_id', name='uk_sys_role_data_scope')
    )
    with op.batch_alter_table('sys_role_data_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_role_data_scope_data_scope_id'), ['data_scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_role_data_scope_role_id'), ['role_id'], unique=False)

    op.create_table('transport_node_business_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('business_category_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'business_category_code', name='uk_node_biz_cat')
    )
    with op.batch_alter_table('transport_node_business_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_node_business_category_node_id'), ['node_id'], unique=False)

    op.create_table('transport_node_handling_mode',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('handling_mode_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'handling_mode_code', name='uk_node_handling')
    )
    with op.batch_alter_table('transport_node_handling_mode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_node_handling_mode_node_id'), ['node_id'], unique=False)

    op.create_table('transport_node_packaging_form',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('packaging_form_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'packaging_form_code', name='uk_node_packaging')
    )
    with op.batch_alter_table('transport_node_packaging_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_node_packaging_form_node_id'), ['node_id'], unique=False)

    op.create_table('transport_node_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('business_nature_code', sa.String(length=64), nullable=True),
    sa.Column('channel_depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_draft_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('berth_count', sa.Integer(), nullable=True),
    sa.Column('annual_throughput_ton', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_hours_desc', sa.String(length=128), nullable=True),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('ext_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('commodity_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_name', sa.String(length=128), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'alias_name', name='uk_commodity_alias')
    )
    with op.batch_alter_table('commodity_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_alias_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('commodity_handling_mode_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('handling_mode_code', sa.String(length=64), nullable=False),
    sa.Column('allow_flag', sa.Boolean(), nullable=False),
    sa.Column('rule_desc', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'handling_mode_code', name='uk_commodity_handling_mode_rule')
    )
    with op.batch_alter_table('commodity_handling_mode_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_handling_mode_rule_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('commodity_node_type_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('node_type_code', sa.String(length=64), nullable=False),
    sa.Column('allow_flag', sa.Boolean(), nullable=False),
    sa.Column('rule_desc', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'node_type_code', name='uk_commodity_node_type_rule')
    )
    with op.batch_alter_table('commodity_node_type_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_node_type_rule_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('commodity_packaging_form',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('packaging_form_code', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'packaging_form_code', name='uk_commodity_packaging_form')
    )
    with op.batch_alter_table('commodity_packaging_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_packaging_form_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('commodity_ship_type_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('ship_type_code', sa.String(length=64), nullable=False),
    sa.Column('allow_flag', sa.Boolean(), nullable=False),
    sa.Column('rule_desc', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'ship_type_code', name='uk_commodity_ship_type_rule')
    )
    with op.batch_alter_table('commodity_ship_type_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_ship_type_rule_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('commodity_standard_attribute',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('attribute_code', sa.String(length=64), nullable=False),
    sa.Column('attribute_name', sa.String(length=128), nullable=False),
    sa.Column('attribute_value_type_code', sa.String(length=64), nullable=False),
    sa.Column('attribute_unit', sa.String(length=32), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=128), nullable=True),
    sa.Column('value_range_desc', sa.String(length=256), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'attribute_code', name='uk_commodity_attribute_code')
    )
    with op.batch_alter_table('commodity_standard_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_standard_attribute_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('commodity_transport_mode',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('transport_mode_element_code', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_standard_id', 'transport_mode_element_code', name='uk_commodity_transport_mode')
    )
    with op.batch_alter_table('commodity_transport_mode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_transport_mode_commodity_standard_id'), ['commodity_standard_id'], unique=False)

    op.create_table('freight',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('freight_no', sa.String(length=32), nullable=False),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('cargo_title', sa.String(length=256), nullable=False),
    sa.Column('cargo_description', sa.String(length=1024), nullable=True),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('packaging_form_code', sa.String(length=64), nullable=True),
    sa.Column('estimated_tonnage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('min_tonnage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_tonnage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_unit', sa.String(length=32), nullable=True),
    sa.Column('settlement_method_code', sa.String(length=64), nullable=True),
    sa.Column('origin_node_id', sa.BigInteger(), nullable=True),
    sa.Column('destination_node_id', sa.BigInteger(), nullable=True),
    sa.Column('origin_province_code', sa.String(length=12), nullable=False),
    sa.Column('origin_city_code', sa.String(length=12), nullable=False),
    sa.Column('origin_district_code', sa.String(length=12), nullable=True),
    sa.Column('destination_province_code', sa.String(length=12), nullable=False),
    sa.Column('destination_city_code', sa.String(length=12), nullable=False),
    sa.Column('destination_district_code', sa.String(length=12), nullable=True),
    sa.Column('origin_region_id_cache', sa.BigInteger(), nullable=True),
    sa.Column('destination_region_id_cache', sa.BigInteger(), nullable=True),
    sa.Column('loading_time_from', sa.DateTime(), nullable=True),
    sa.Column('loading_time_to', sa.DateTime(), nullable=True),
    sa.Column('unloading_time_from', sa.DateTime(), nullable=True),
    sa.Column('unloading_time_to', sa.DateTime(), nullable=True),
    sa.Column('publisher_org_name', sa.String(length=128), nullable=True),
    sa.Column('status_code', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.ForeignKeyConstraint(['destination_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['destination_region_id_cache'], ['region.id'], ),
    sa.ForeignKeyConstraint(['origin_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['origin_region_id_cache'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freight_no')
    )
    with op.batch_alter_table('freight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freight_commodity_standard_id'), ['commodity_standard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_freight_destination_node_id'), ['destination_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_freight_destination_region_id_cache'), ['destination_region_id_cache'], unique=False)
        batch_op.create_index(batch_op.f('ix_freight_origin_node_id'), ['origin_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_freight_origin_region_id_cache'), ['origin_region_id_cache'], unique=False)

    op.create_table('shipping_route_plan_segment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_no', sa.Integer(), nullable=False),
    sa.Column('segment_type_code', sa.String(length=64), nullable=False),
    sa.Column('start_node_id', sa.BigInteger(), nullable=True),
    sa.Column('end_node_id', sa.BigInteger(), nullable=True),
    sa.Column('start_constraint_point_id', sa.BigInteger(), nullable=True),
    sa.Column('end_constraint_point_id', sa.BigInteger(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_duration_hour', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('geometry_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['end_constraint_point_id'], ['navigation_constraint_point.id'], ),
    sa.ForeignKeyConstraint(['end_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['shipping_route_plan.id'], ),
    sa.ForeignKeyConstraint(['start_constraint_point_id'], ['navigation_constraint_point.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'segment_no', name='uk_route_plan_segment_no')
    )
    with op.batch_alter_table('shipping_route_plan_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_route_plan_segment_plan_id'), ['plan_id'], unique=False)

    op.create_table('stat_cargo_commodity_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('commodity_standard_id', sa.BigInteger(), nullable=False),
    sa.Column('freight_count', sa.Integer(), nullable=False),
    sa.Column('tonnage', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('avg_unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_standard_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_cargo_commodity_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_cargo_commodity_daily_commodity_standard_id'), ['commodity_standard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_cargo_commodity_daily_stat_date'), ['stat_date'], unique=False)

    op.create_table('freight_contact',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('freight_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('contact_role_code', sa.String(length=64), nullable=False),
    sa.Column('mobile_phone', sa.String(length=32), nullable=True),
    sa.Column('landline_phone', sa.String(length=32), nullable=True),
    sa.Column('wechat', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['freight_id'], ['freight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freight_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freight_contact_freight_id'), ['freight_id'], unique=False)

    op.create_table('freight_source_attachment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('freight_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_provider_code', sa.String(length=64), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_ext', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('source_type_code', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_id'], ['freight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freight_source_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freight_source_attachment_freight_id'), ['freight_id'], unique=False)

    op.create_table('freight_tag_relation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('freight_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_id'], ['freight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freight_tag_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freight_tag_relation_freight_id'), ['freight_id'], unique=False)

    op.create_table('shipping_route_plan_segment_point',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('point_no', sa.Integer(), nullable=False),
    sa.Column('point_type_code', sa.String(length=64), nullable=False),
    sa.Column('related_node_id', sa.BigInteger(), nullable=True),
    sa.Column('related_constraint_point_id', sa.BigInteger(), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('stay_minutes', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_constraint_point_id'], ['navigation_constraint_point.id'], ),
    sa.ForeignKeyConstraint(['related_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['shipping_route_plan_segment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'point_no', name='uk_route_segment_point_no')
    )
    with op.batch_alter_table('shipping_route_plan_segment_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_route_plan_segment_point_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipping_route_plan_segment_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_route_plan_segment_point_segment_id'))

    op.drop_table('shipping_route_plan_segment_point')
    with op.batch_alter_table('freight_tag_relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freight_tag_relation_freight_id'))

    op.drop_table('freight_tag_relation')
    with op.batch_alter_table('freight_source_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freight_source_attachment_freight_id'))

    op.drop_table('freight_source_attachment')
    with op.batch_alter_table('freight_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freight_contact_freight_id'))

    op.drop_table('freight_contact')
    with op.batch_alter_table('stat_cargo_commodity_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_cargo_commodity_daily_stat_date'))
        batch_op.drop_index(batch_op.f('ix_stat_cargo_commodity_daily_commodity_standard_id'))

    op.drop_table('stat_cargo_commodity_daily')
    with op.batch_alter_table('shipping_route_plan_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_route_plan_segment_plan_id'))

    op.drop_table('shipping_route_plan_segment')
    with op.batch_alter_table('freight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freight_origin_region_id_cache'))
        batch_op.drop_index(batch_op.f('ix_freight_origin_node_id'))
        batch_op.drop_index(batch_op.f('ix_freight_destination_region_id_cache'))
        batch_op.drop_index(batch_op.f('ix_freight_destination_node_id'))
        batch_op.drop_index(batch_op.f('ix_freight_commodity_standard_id'))

    op.drop_table('freight')
    with op.batch_alter_table('commodity_transport_mode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_transport_mode_commodity_standard_id'))

    op.drop_table('commodity_transport_mode')
    with op.batch_alter_table('commodity_standard_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_standard_attribute_commodity_standard_id'))

    op.drop_table('commodity_standard_attribute')
    with op.batch_alter_table('commodity_ship_type_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_ship_type_rule_commodity_standard_id'))

    op.drop_table('commodity_ship_type_rule')
    with op.batch_alter_table('commodity_packaging_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_packaging_form_commodity_standard_id'))

    op.drop_table('commodity_packaging_form')
    with op.batch_alter_table('commodity_node_type_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_node_type_rule_commodity_standard_id'))

    op.drop_table('commodity_node_type_rule')
    with op.batch_alter_table('commodity_handling_mode_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_handling_mode_rule_commodity_standard_id'))

    op.drop_table('commodity_handling_mode_rule')
    with op.batch_alter_table('commodity_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_alias_commodity_standard_id'))

    op.drop_table('commodity_alias')
    op.drop_table('transport_node_profile')
    with op.batch_alter_table('transport_node_packaging_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_node_packaging_form_node_id'))

    op.drop_table('transport_node_packaging_form')
    with op.batch_alter_table('transport_node_handling_mode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_node_handling_mode_node_id'))

    op.drop_table('transport_node_handling_mode')
    with op.batch_alter_table('transport_node_business_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_node_business_category_node_id'))

    op.drop_table('transport_node_business_category')
    with op.batch_alter_table('sys_role_data_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_role_data_scope_role_id'))
        batch_op.drop_index(batch_op.f('ix_sys_role_data_scope_data_scope_id'))

    op.drop_table('sys_role_data_scope')
    with op.batch_alter_table('shipping_route_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_route_plan_route_id'))

    op.drop_table('shipping_route_plan')
    with op.batch_alter_table('ship_import_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_import_record_ship_id'))
        batch_op.drop_index(batch_op.f('ix_ship_import_record_raw_id'))
        batch_op.drop_index(batch_op.f('ix_ship_import_record_batch_id'))

    op.drop_table('ship_import_record')
    with op.batch_alter_table('ship_certificate_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_certificate_file_ship_certificate_id'))

    op.drop_table('ship_certificate_file')
    with op.batch_alter_table('node_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_alias_node_id'))

    op.drop_table('node_alias')
    with op.batch_alter_table('commodity_standard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_standard_type_id'))

    op.drop_table('commodity_standard')
    with op.batch_alter_table('transport_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_node_city_region_id'))

    op.drop_table('transport_node')
    with op.batch_alter_table('sys_user_status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_user_status_log_user_id'))

    op.drop_table('sys_user_status_log')
    with op.batch_alter_table('sys_user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_user_role_user_id'))
        batch_op.drop_index(batch_op.f('ix_sys_user_role_role_id'))

    op.drop_table('sys_user_role')
    with op.batch_alter_table('sys_role_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_role_permission_role_id'))
        batch_op.drop_index(batch_op.f('ix_sys_role_permission_permission_id'))

    op.drop_table('sys_role_permission')
    with op.batch_alter_table('sys_role_menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_role_menu_role_id'))
        batch_op.drop_index(batch_op.f('ix_sys_role_menu_menu_id'))

    op.drop_table('sys_role_menu')
    with op.batch_alter_table('sys_login_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_login_log_user_id'))

    op.drop_table('sys_login_log')
    op.drop_table('sys_data_scope')
    with op.batch_alter_table('std_dict_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_std_dict_item_dict_id'))

    op.drop_table('std_dict_item')
    with op.batch_alter_table('shipping_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_route_origin_region_id'))
        batch_op.drop_index(batch_op.f('ix_shipping_route_destination_region_id'))

    op.drop_table('shipping_route')
    with op.batch_alter_table('ship_owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_owner_ship_id'))

    op.drop_table('ship_owner')
    op.drop_table('ship_operation')
    with op.batch_alter_table('ship_name_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_name_history_ship_id'))

    op.drop_table('ship_name_history')
    with op.batch_alter_table('ship_mmsi_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_mmsi_history_ship_id'))

    op.drop_table('ship_mmsi_history')
    with op.batch_alter_table('ship_import_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_import_raw_batch_id'))

    op.drop_table('ship_import_raw')
    op.drop_table('ship_dynamic')
    with op.batch_alter_table('ship_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_contact_ship_id'))

    op.drop_table('ship_contact')
    with op.batch_alter_table('ship_certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_certificate_ship_id'))

    op.drop_table('ship_certificate')
    op.drop_table('ship_capacity')
    with op.batch_alter_table('region_city_relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_city_relation_region_id'))
        batch_op.drop_index(batch_op.f('ix_region_city_relation_city_region_id'))

    op.drop_table('region_city_relation')
    with op.batch_alter_table('region_boundary_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_boundary_version_region_id'))

    op.drop_table('region_boundary_version')
    with op.batch_alter_table('commodity_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_type_category_id'))

    op.drop_table('commodity_type')
    with op.batch_alter_table('audit_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_record_task_id'))

    op.drop_table('audit_record')
    with op.batch_alter_table('admin_region_boundary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_region_boundary_admin_region_id'))

    op.drop_table('admin_region_boundary')
    op.drop_table('system_config')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('sys_menu')
    op.drop_table('std_dict')
    with op.batch_alter_table('stat_ship_flow_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_ship_flow_daily_stat_date'))
        batch_op.drop_index(batch_op.f('ix_stat_ship_flow_daily_origin_city_code'))
        batch_op.drop_index(batch_op.f('ix_stat_ship_flow_daily_destination_city_code'))

    op.drop_table('stat_ship_flow_daily')
    with op.batch_alter_table('stat_ship_city_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_ship_city_daily_stat_date'))
        batch_op.drop_index(batch_op.f('ix_stat_ship_city_daily_city_code'))

    op.drop_table('stat_ship_city_daily')
    with op.batch_alter_table('stat_job_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_job_run_stat_date'))
        batch_op.drop_index(batch_op.f('ix_stat_job_run_job_code'))

    op.drop_table('stat_job_run')
    with op.batch_alter_table('stat_cargo_flow_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_cargo_flow_daily_stat_date'))
        batch_op.drop_index(batch_op.f('ix_stat_cargo_flow_daily_origin_city_code'))
        batch_op.drop_index(batch_op.f('ix_stat_cargo_flow_daily_destination_city_code'))

    op.drop_table('stat_cargo_flow_daily')
    with op.batch_alter_table('stat_cargo_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_cargo_daily_stat_date'))

    op.drop_table('stat_cargo_daily')
    with op.batch_alter_table('stat_cargo_city_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_cargo_city_daily_stat_date'))
        batch_op.drop_index(batch_op.f('ix_stat_cargo_city_daily_city_code'))

    op.drop_table('stat_cargo_city_daily')
    op.drop_table('ship_profile')
    op.drop_table('ship_import_batch')
    op.drop_table('region')
    with op.batch_alter_table('navigation_constraint_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_navigation_constraint_profile_constraint_point_id'))

    op.drop_table('navigation_constraint_profile')
    op.drop_table('navigation_constraint_point')
    op.drop_table('commodity_category')
    op.drop_table('code_sequence')
    with op.batch_alter_table('cargo_channel_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cargo_channel_daily_stat_date'))
        batch_op.drop_index(batch_op.f('ix_cargo_channel_daily_source_type_code'))

    op.drop_table('cargo_channel_daily')
    with op.batch_alter_table('audit_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_task_biz_id'))

    op.drop_table('audit_task')
    with op.batch_alter_table('admin_region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_region_parent_code'))

    op.drop_table('admin_region')
    # ### end Alembic commands ###
