"""phase1 baseline schema

Revision ID: c878ba817509
Revises: 
Create Date: 2026-03-19 18:18:53.715069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c878ba817509'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False, comment='行政区划代码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
    sa.Column('short_name', sa.String(length=32), nullable=True, comment='简称'),
    sa.Column('pinyin', sa.String(length=128), nullable=True, comment='拼音'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='1=省,2=市,3=区县'),
    sa.Column('parent_code', sa.String(length=12), nullable=True, comment='上级代码'),
    sa.Column('full_path', sa.String(length=256), nullable=True, comment='完整路径'),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='行政中心经度'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='行政中心纬度'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['admin_region.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ai_prompt_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='模板唯一标识，如 cargo_parse'),
    sa.Column('use_case', sa.String(length=64), nullable=True, comment='使用场景'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板详细说明'),
    sa.Column('active_version', sa.Integer(), nullable=False, comment='当前生效的版本号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False 时不可被调用'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False, comment='审核对象类型: TRANSPORT_NODE/COMMODITY_CATEGORY/COMMODITY_TYPE/COMMODITY_STANDARD/VESSEL/WATERWAY/REGION/NODE_TYPE/CARGO_OPPORTUNITY'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='被审核对象ID'),
    sa.Column('target_name', sa.String(length=256), nullable=True, comment='被审核对象名称（快照）'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='操作类型: CREATE/UPDATE/DISABLE/ENABLE/AI_CONFIRM'),
    sa.Column('before_data', sa.JSON(), nullable=True, comment='变更前数据快照'),
    sa.Column('after_data', sa.JSON(), nullable=True, comment='变更后数据快照（提交内容）'),
    sa.Column('audit_result', sa.String(length=32), nullable=False, comment='PENDING/APPROVED/REJECTED'),
    sa.Column('audit_remark', sa.String(length=512), nullable=True, comment='审核意见'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=False, comment='提交人ID'),
    sa.Column('submitter_name', sa.String(length=64), nullable=True, comment='提交人姓名（快照）'),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='提交时间'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('auditor_name', sa.String(length=64), nullable=True, comment='审核人姓名（快照）'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False, comment='审核对象类型: WATERWAY/REGION/TRANSPORT_NODE/NODE_TYPE/VESSEL/VESSEL_TYPE/COMMODITY_CATEGORY/COMMODITY_TYPE/COMMODITY_STANDARD/CARGO_OPPORTUNITY'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='被审核对象ID'),
    sa.Column('target_name', sa.String(length=256), nullable=True, comment='被审核对象名称（快照）'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='CREATE/UPDATE'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending=待审核, approved=已通过, rejected=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=False, comment='提交人ID'),
    sa.Column('submit_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='提交时间'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audit_time', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('remark', sa.String(length=512), nullable=True, comment='审核意见'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_task_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_task_target_type'), ['target_type'], unique=False)

    op.create_table('cargo_channel_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='TMS/WECHAT_AI/MANUAL'),
    sa.Column('raw_msg_count', sa.Integer(), nullable=False, comment='原始消息/消费数量'),
    sa.Column('parse_success_count', sa.Integer(), nullable=False, comment='AI解析成功数量（WECHAT_AI专用）'),
    sa.Column('confirmed_count', sa.Integer(), nullable=False, comment='最终确认货源数量'),
    sa.Column('total_tonnage', sa.DECIMAL(precision=16, scale=2), nullable=False, comment='确认货源总吨位(吨)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'source_type', name='uk_cargo_channel_daily')
    )
    with op.batch_alter_table('cargo_channel_daily', schema=None) as batch_op:
        batch_op.create_index('ix_cargo_channel_date', ['stat_date'], unique=False)

    op.create_table('cargo_city_heatmap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('city_code', sa.String(length=12), nullable=False, comment='城市行政区划代码'),
    sa.Column('city_name', sa.String(length=50), nullable=False, comment='城市名称（冗余）'),
    sa.Column('city_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='城市中心经度（来自admin_region）'),
    sa.Column('city_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='城市中心纬度（来自admin_region）'),
    sa.Column('stat_type', sa.String(length=8), nullable=False, comment='ORIGIN=装货城市热力, DEST=卸货城市热力'),
    sa.Column('cargo_count', sa.Integer(), nullable=False, comment='货源数量'),
    sa.Column('total_tonnage', sa.DECIMAL(precision=16, scale=2), nullable=False, comment='总吨位(吨)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'city_code', 'stat_type', name='uk_cargo_city_heatmap')
    )
    with op.batch_alter_table('cargo_city_heatmap', schema=None) as batch_op:
        batch_op.create_index('ix_cargo_city_heatmap_city', ['city_code'], unique=False)
        batch_op.create_index('ix_cargo_city_heatmap_date', ['stat_date'], unique=False)

    op.create_table('cargo_od_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('origin_city_code', sa.String(length=12), nullable=False, comment='起点城市行政区划代码'),
    sa.Column('origin_city_name', sa.String(length=50), nullable=False, comment='起点城市名称（冗余）'),
    sa.Column('dest_city_code', sa.String(length=12), nullable=False, comment='终点城市行政区划代码'),
    sa.Column('dest_city_name', sa.String(length=50), nullable=False, comment='终点城市名称（冗余）'),
    sa.Column('cargo_count', sa.Integer(), nullable=False, comment='货源数量'),
    sa.Column('total_tonnage', sa.DECIMAL(precision=16, scale=2), nullable=False, comment='总吨位(吨)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'origin_city_code', 'dest_city_code', name='uk_cargo_od_daily')
    )
    with op.batch_alter_table('cargo_od_daily', schema=None) as batch_op:
        batch_op.create_index('ix_cargo_od_date', ['stat_date'], unique=False)
        batch_op.create_index('ix_cargo_od_origin', ['origin_city_code'], unique=False)

    op.create_table('cargo_raw_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='原始文本内容'),
    sa.Column('source_type', sa.String(length=32), nullable=True, comment='WECHAT_GROUP/WECHAT_PRIVATE/SMS/OTHER'),
    sa.Column('group_name', sa.String(length=128), nullable=True, comment='群名称'),
    sa.Column('sender_name', sa.String(length=64), nullable=True, comment='发送人'),
    sa.Column('message_time', sa.DateTime(), nullable=True, comment='消息时间'),
    sa.Column('collector_id', sa.BigInteger(), nullable=True, comment='采集员ID'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='PENDING/PARSING/PARSED/PARSE_FAILED/INVALID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_stat_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期（每日唯一）'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='当日新增货源总量'),
    sa.Column('confirmed_count', sa.Integer(), nullable=False, comment='CONFIRMED状态货源数量'),
    sa.Column('pending_count', sa.Integer(), nullable=False, comment='PENDING状态货源数量'),
    sa.Column('total_tonnage', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='当日新增总吨位(吨)'),
    sa.Column('avg_tonnage', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='平均吨位(吨)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date')
    )
    with op.batch_alter_table('cargo_stat_daily', schema=None) as batch_op:
        batch_op.create_index('ix_cargo_stat_date', ['stat_date'], unique=False)

    op.create_table('commodity_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True, comment='分类编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='大类名称'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名称'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='类型编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='类型名称'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名称'),
    sa.Column('transport_mode', sa.String(length=32), nullable=False, comment='WATERWAY/RAILWAY/HIGHWAY/MULTIMODAL'),
    sa.Column('icon', sa.String(length=256), nullable=True, comment='图标URL'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='区域编码（系统自动生成，格式 RG-NNN）'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='区域名称'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名称'),
    sa.Column('center_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='区域中心经度（由边界坐标自动计算）'),
    sa.Column('center_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='区域中心纬度（由边界坐标自动计算）'),
    sa.Column('main_rivers', sa.JSON(), nullable=True, comment='(弃用) 主要水系ID数组，正式关系见 region_waterway_relation'),
    sa.Column('main_rivers_names', sa.JSON(), nullable=True, comment='(弃用) 主要水系名称数组'),
    sa.Column('main_cities', sa.JSON(), nullable=True, comment='(弃用) 主要城市ID数组，正式关系见 region_city_relation'),
    sa.Column('main_cities_names', sa.JSON(), nullable=True, comment='(弃用) 主要城市名称数组'),
    sa.Column('boundary_coordinates', sa.JSON(), nullable=True, comment='边界坐标点序列 [[lng,lat],...]'),
    sa.Column('boundary_color', sa.String(length=20), nullable=True, comment='边界颜色'),
    sa.Column('area_color', sa.String(length=20), nullable=True, comment='填充颜色'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用,0=停用'),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('audit_remark', sa.String(length=512), nullable=True, comment='审核意见'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ship_stat_age',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age_range_label', sa.String(length=32), nullable=False, comment="船龄档位，如 '6-10年'"),
    sa.Column('min_age', sa.Integer(), nullable=True, comment='区间下限（NULL=无下限）'),
    sa.Column('max_age', sa.Integer(), nullable=True, comment='区间上限（NULL=无上限）'),
    sa.Column('vessel_count', sa.Integer(), nullable=False, comment='该区间船舶数量'),
    sa.Column('ratio', sa.DECIMAL(precision=6, scale=3), nullable=False, comment='占全部有效船舶的百分比'),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True, comment='最近刷新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_stat_age', schema=None) as batch_op:
        batch_op.create_index('ix_ship_stat_age_label', ['age_range_label'], unique=True)

    op.create_table('ship_stat_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_code', sa.String(length=12), nullable=False, comment='admin_region.code（冗余，无FK约束）'),
    sa.Column('city_name', sa.String(length=64), nullable=False, comment='城市名称（冗余）'),
    sa.Column('province_name', sa.String(length=64), nullable=True, comment='省份名称（冗余，用于省级聚合）'),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='城市行政中心经度（来自admin_region）'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='城市行政中心纬度（来自admin_region）'),
    sa.Column('vessel_count', sa.Integer(), nullable=False, comment='该城市范围内船舶数量'),
    sa.Column('total_deadweight', sa.DECIMAL(precision=16, scale=2), nullable=False, comment='城市运力：合计载重吨(DWT)'),
    sa.Column('ratio', sa.DECIMAL(precision=6, scale=3), nullable=False, comment='占全部有位置船舶的百分比'),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True, comment='最近刷新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_stat_city', schema=None) as batch_op:
        batch_op.create_index('ix_ship_stat_city_code', ['city_code'], unique=True)

    op.create_table('ship_stat_dwt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_label', sa.String(length=32), nullable=False, comment="档位标签，如 '500-1000吨'"),
    sa.Column('min_dwt', sa.Integer(), nullable=True, comment='区间下限（NULL=无下限）'),
    sa.Column('max_dwt', sa.Integer(), nullable=True, comment='区间上限（NULL=无上限）'),
    sa.Column('vessel_count', sa.Integer(), nullable=False, comment='该区间船舶数量'),
    sa.Column('ratio', sa.DECIMAL(precision=6, scale=3), nullable=False, comment='占全部有效船舶的百分比'),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True, comment='最近刷新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_stat_dwt', schema=None) as batch_op:
        batch_op.create_index('ix_ship_stat_dwt_label', ['segment_label'], unique=True)

    op.create_table('ship_stat_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='Region.id（冗余，无FK约束）'),
    sa.Column('region_name', sa.String(length=64), nullable=False, comment='区域名称（冗余）'),
    sa.Column('center_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='区域中心经度（冗余）'),
    sa.Column('center_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='区域中心纬度（冗余）'),
    sa.Column('boundary_coordinates', sa.JSON(), nullable=True, comment='边界坐标 [[lng,lat],...]，冗余供前端绘图'),
    sa.Column('vessel_count', sa.Integer(), nullable=False, comment='区域内船舶总数'),
    sa.Column('total_deadweight', sa.DECIMAL(precision=16, scale=2), nullable=False, comment='区域运力：合计载重吨(DWT)'),
    sa.Column('ratio', sa.DECIMAL(precision=6, scale=3), nullable=False, comment='占全部有位置船舶的百分比'),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True, comment='最近刷新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ship_stat_region', schema=None) as batch_op:
        batch_op.create_index('ix_ship_stat_region_id', ['region_id'], unique=True)

    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='SUPER_ADMIN/ADMIN/OPERATOR/COLLECTOR'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='角色描述'),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名（登录名）'),
    sa.Column('real_name', sa.String(length=64), nullable=False, comment='真实姓名'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码哈希'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('avatar', sa.String(length=256), nullable=True, comment='头像URL'),
    sa.Column('wx_open_id', sa.String(length=64), nullable=True, comment='微信OpenID'),
    sa.Column('wx_bound', sa.SmallInteger(), nullable=True, comment='0=未绑定,1=已绑定'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用,0=停用'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vessel_type_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='船型编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='船型名称'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名称'),
    sa.Column('transport_type', sa.String(length=32), nullable=True, comment='运输类型'),
    sa.Column('applicable_goods', sa.JSON(), nullable=True, comment='适用货品类型'),
    sa.Column('min_tonnage', sa.Integer(), nullable=True, comment='最小载重吨(DWT)'),
    sa.Column('max_tonnage', sa.Integer(), nullable=True, comment='最大载重吨(DWT)'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('waterway',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='水系编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='水系名称'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名称'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='1=主干水系,2=支流,3=运河'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级水系ID'),
    sa.Column('provinces', sa.String(length=256), nullable=True, comment='流经省份'),
    sa.Column('total_length_km', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='总长度(km)'),
    sa.Column('navigable_length_km', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='通航里程(km)'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用,0=停用'),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['waterway.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ai_prompt_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号，从 1 递增'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='系统提示词正文'),
    sa.Column('user_template', sa.Text(), nullable=False, comment='用户消息模板，用 {变量名} 作占位符'),
    sa.Column('change_note', sa.String(length=512), nullable=True, comment='本次变更说明'),
    sa.Column('call_count', sa.Integer(), nullable=False, comment='总调用次数'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='调用成功次数'),
    sa.Column('confirm_count', sa.Integer(), nullable=False, comment='被人工无修改直接确认次数（AI 完全正确）'),
    sa.Column('correction_count', sa.Integer(), nullable=False, comment='被人工修正后确认次数（AI 有误）'),
    sa.Column('avg_confidence', sa.Float(), nullable=False, comment='历次调用平均置信度（滚动更新）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True, comment='废弃时间，NULL=仍可用'),
    sa.ForeignKeyConstraint(['template_id'], ['ai_prompt_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_commodity_stat_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('commodity_category_id', sa.BigInteger(), nullable=False, comment='货品大类ID'),
    sa.Column('category_name', sa.String(length=64), nullable=False, comment='货品大类名称（冗余存储）'),
    sa.Column('cargo_count', sa.Integer(), nullable=False, comment='货源数量'),
    sa.Column('total_tonnage', sa.DECIMAL(precision=16, scale=2), nullable=False, comment='总吨位(吨)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['commodity_category_id'], ['commodity_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'commodity_category_id', name='uk_cargo_commodity_stat')
    )
    with op.batch_alter_table('cargo_commodity_stat_daily', schema=None) as batch_op:
        batch_op.create_index('ix_cargo_commodity_stat_cat', ['commodity_category_id'], unique=False)
        batch_op.create_index('ix_cargo_commodity_stat_date', ['stat_date'], unique=False)

    op.create_table('commodity_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True, comment='类型编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='类型名称'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名称'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['commodity_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_city_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_region_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False, comment='MAIN/COVERED/RELATED'),
    sa.Column('is_primary', sa.SmallInteger(), nullable=False, comment='1=主关系'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='RULE/AI/MANUAL/SYNC'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_region_id'], ['admin_region.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'admin_region_id', name='uk_region_city_relation')
    )
    with op.batch_alter_table('region_city_relation', schema=None) as batch_op:
        batch_op.create_index('ix_region_city_region', ['region_id'], unique=False)

    op.create_table('region_waterway_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('waterway_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False, comment='MAIN/RELATED'),
    sa.Column('is_primary', sa.SmallInteger(), nullable=False, comment='1=主关系'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='RULE/AI/MANUAL/SYNC'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['waterway_id'], ['waterway.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'waterway_id', name='uk_region_waterway_relation')
    )
    with op.batch_alter_table('region_waterway_relation', schema=None) as batch_op:
        batch_op.create_index('ix_region_waterway_region', ['region_id'], unique=False)

    op.create_table('shipping_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='航线编码，自动生成 RT-XXXXXXXXXXXX'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='航线名称'),
    sa.Column('origin_region_id', sa.BigInteger(), nullable=False, comment='起始区域'),
    sa.Column('dest_region_id', sa.BigInteger(), nullable=False, comment='目的区域'),
    sa.Column('distance_km', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='参考距离(km)'),
    sa.Column('duration_hours', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='标准航行时长(小时)'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='航线描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用,0=停用'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dest_region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['origin_region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='节点编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='节点标准名称'),
    sa.Column('name_en', sa.String(length=256), nullable=True, comment='英文名称'),
    sa.Column('node_type_id', sa.BigInteger(), nullable=False),
    sa.Column('node_category', sa.SmallInteger(), nullable=False, comment='1=装货,2=卸货,3=中转,4=综合,5=航道'),
    sa.Column('waterway_id', sa.BigInteger(), nullable=True, comment='所属水系'),
    sa.Column('region_id', sa.BigInteger(), nullable=True, comment='(弃用) 单值区域归属'),
    sa.Column('province_code', sa.String(length=12), nullable=True, comment='省级行政区划代码'),
    sa.Column('city_code', sa.String(length=12), nullable=True, comment='市级行政区划代码'),
    sa.Column('district_code', sa.String(length=12), nullable=True, comment='区县级行政区划代码'),
    sa.Column('province', sa.String(length=32), nullable=True, comment='所属省份'),
    sa.Column('city', sa.String(length=32), nullable=True, comment='所属城市'),
    sa.Column('district', sa.String(length=32), nullable=True, comment='所属区县'),
    sa.Column('address', sa.String(length=256), nullable=True, comment='详细地址'),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='经度(WGS84)'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='纬度(WGS84)'),
    sa.Column('node_level', sa.SmallInteger(), nullable=True, comment='1=一级,2=二级,3=三级'),
    sa.Column('is_hot_node', sa.SmallInteger(), nullable=False, comment='0=否,1=是'),
    sa.Column('river_km', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='航道里程标(km)'),
    sa.Column('max_tonnage', sa.Integer(), nullable=True, comment='最大靠泊吨位(吨)'),
    sa.Column('berth_count', sa.Integer(), nullable=True, comment='泊位数量'),
    sa.Column('annual_throughput', sa.String(length=64), nullable=True, comment='年吞吐量'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=运营中,0=停用,2=建设中'),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('audit_remark', sa.String(length=512), nullable=True, comment='审核意见'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_type.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['waterway_id'], ['waterway.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vessel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_no', sa.String(length=64), nullable=False, comment='船舶检验证书号(业务唯一标识)'),
    sa.Column('vessel_name', sa.String(length=128), nullable=False, comment='当前船名'),
    sa.Column('mmsi', sa.String(length=20), nullable=True, comment='AIS编号/MMSI'),
    sa.Column('call_sign', sa.String(length=32), nullable=True, comment='船舶呼号'),
    sa.Column('vessel_type_id', sa.BigInteger(), nullable=True, comment='船舶类型'),
    sa.Column('deadweight', sa.Integer(), nullable=True, comment='载重吨(DWT)'),
    sa.Column('gross_tonnage', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='总吨'),
    sa.Column('net_tonnage', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='净吨'),
    sa.Column('length', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='船长(m)'),
    sa.Column('breadth', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='船宽(m)'),
    sa.Column('depth', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='型深(m)'),
    sa.Column('max_draft', sa.DECIMAL(precision=8, scale=3), nullable=True, comment='最大吃水(m)'),
    sa.Column('build_year', sa.Integer(), nullable=True, comment='建造年份'),
    sa.Column('build_country', sa.String(length=64), nullable=True, comment='建造国家'),
    sa.Column('build_city', sa.String(length=64), nullable=True, comment='建造地'),
    sa.Column('home_port', sa.String(length=128), nullable=True, comment='船籍港'),
    sa.Column('flag', sa.String(length=32), nullable=True, comment='船旗国'),
    sa.Column('owner_name', sa.String(length=128), nullable=True, comment='船东名称'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('data_status', sa.SmallInteger(), nullable=True, comment='1=有效,0=注销'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('audit_remark', sa.String(length=512), nullable=True, comment='审核意见'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vessel_type_id'], ['vessel_type_dict.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_no')
    )
    op.create_table('commodity_standard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True, comment='货品编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='货品标准名称'),
    sa.Column('name_en', sa.String(length=256), nullable=True, comment='英文名称'),
    sa.Column('commodity_class', sa.String(length=32), nullable=True, comment='货品分类:散货/件杂/液体/集装箱/特种'),
    sa.Column('industry', sa.String(length=64), nullable=True, comment='行业分类'),
    sa.Column('density', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='密度(t/m³)'),
    sa.Column('default_density', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='默认密度(t/m³)'),
    sa.Column('is_dangerous', sa.SmallInteger(), nullable=True, comment='0=否,1=是'),
    sa.Column('danger_level', sa.String(length=32), nullable=True, comment='危险等级：NONE/LOW/MEDIUM/HIGH'),
    sa.Column('common_unit', sa.String(length=32), nullable=True, comment='常用计量单位：吨/方/箱'),
    sa.Column('loading_method', sa.String(length=64), nullable=True, comment='装货方式'),
    sa.Column('recommended_ship_type', sa.String(length=128), nullable=True, comment='推荐船型'),
    sa.Column('match_keywords', sa.JSON(), nullable=True, comment='规则匹配关键词列表'),
    sa.Column('match_regex', sa.String(length=256), nullable=True, comment='规则匹配正则'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='MANUAL/AI/IMPORT/TMS'),
    sa.Column('confidence', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='标准命中置信度(0-100)'),
    sa.Column('is_ai_generated', sa.SmallInteger(), nullable=True, comment='是否AI生成候选'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('audit_remark', sa.String(length=512), nullable=True, comment='审核意见'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['commodity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_name', sa.String(length=128), nullable=False, comment='别名'),
    sa.Column('alias_type', sa.String(length=32), nullable=False, comment='COMMON/ABBR/HISTORICAL/SYSTEM'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='别名来源'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='匹配优先级'),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间，NULL=未删除'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name')
    )
    op.create_table('region_address_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('transport_node_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False, comment='PRIMARY/SECONDARY/PASSING/COVERED'),
    sa.Column('is_primary', sa.SmallInteger(), nullable=False, comment='1=主归属'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='RULE/AI/MANUAL/SYNC'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['transport_node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'transport_node_id', name='uk_region_node_relation')
    )
    with op.batch_alter_table('region_address_relation', schema=None) as batch_op:
        batch_op.create_index('ix_region_address_node', ['transport_node_id'], unique=False)

    op.create_table('shipping_route_path',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False, comment='所属航线ID'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='路线编码，自动生成 RP-XXXXXXXXXXXX'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='路线名称，如主航道/运河绕行线'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='路线描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序，数字越小越靠前'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1=启用,0=停用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['shipping_route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vessel_ais_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.BigInteger(), nullable=False),
    sa.Column('old_mmsi', sa.String(length=20), nullable=False, comment='原MMSI'),
    sa.Column('new_mmsi', sa.String(length=20), nullable=False, comment='新MMSI'),
    sa.Column('change_reason', sa.String(length=256), nullable=True, comment='变更原因'),
    sa.Column('changed_by', sa.BigInteger(), nullable=True, comment='操作人ID'),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_dynamic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.BigInteger(), nullable=True, comment='每船唯一一条最新动态'),
    sa.Column('mmsi', sa.String(length=20), nullable=True, comment='MMSI号（动态更新的唯一键）'),
    sa.Column('data_source', sa.String(length=32), nullable=False, comment='AIS/MANUAL/IMPORT'),
    sa.Column('reported_at', sa.DateTime(), nullable=True, comment='源系统上报时间'),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='平台接入时间'),
    sa.Column('current_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='当前经度'),
    sa.Column('current_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='当前纬度'),
    sa.Column('current_region_id', sa.BigInteger(), nullable=True, comment='当前归属商业区域'),
    sa.Column('current_city_code', sa.String(length=12), nullable=True, comment='当前归属城市代码'),
    sa.Column('position_match_type', sa.String(length=32), nullable=True, comment='NODE_EXACT/POLYGON_MATCH/CITY_NEAREST/UNKNOWN'),
    sa.Column('position_match_distance_m', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='位置匹配距离(米)'),
    sa.Column('current_node_id', sa.BigInteger(), nullable=True, comment='当前所在节点'),
    sa.Column('vessel_status', sa.String(length=32), nullable=True, comment='EMPTY/LOADED/IN_PORT/ANCHORED/UNDERWAY/MAINTENANCE'),
    sa.Column('current_draft', sa.DECIMAL(precision=8, scale=3), nullable=True, comment='当前吃水(m)'),
    sa.Column('dest_node_id', sa.BigInteger(), nullable=True, comment='目的港节点'),
    sa.Column('eta', sa.DateTime(), nullable=True, comment='预计到达时间'),
    sa.Column('speed', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='当前航速(节)'),
    sa.Column('heading', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='当前船首向(度)'),
    sa.Column('cargo_info', sa.String(length=256), nullable=True, comment='当前载货信息'),
    sa.Column('remark', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['current_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['current_region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['dest_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mmsi'),
    sa.UniqueConstraint('vessel_id')
    )
    op.create_table('vessel_name_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.BigInteger(), nullable=False),
    sa.Column('old_name', sa.String(length=128), nullable=False, comment='原船名'),
    sa.Column('new_name', sa.String(length=128), nullable=False, comment='新船名'),
    sa.Column('change_reason', sa.String(length=256), nullable=True, comment='变更原因'),
    sa.Column('changed_by', sa.BigInteger(), nullable=True, comment='操作人ID'),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='变更时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_ai_parse_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_message_id', sa.BigInteger(), nullable=False),
    sa.Column('origin_text', sa.String(length=256), nullable=True, comment='起点原始文本'),
    sa.Column('dest_text', sa.String(length=256), nullable=True, comment='终点原始文本'),
    sa.Column('commodity_text', sa.String(length=256), nullable=True, comment='货品原始文本'),
    sa.Column('tonnage_text', sa.String(length=64), nullable=True, comment='吨位原始文本'),
    sa.Column('loading_date_text', sa.String(length=64), nullable=True, comment='时间原始文本'),
    sa.Column('freight_text', sa.String(length=128), nullable=True, comment='运价原始文本'),
    sa.Column('contact_text', sa.String(length=256), nullable=True, comment='联系方式原始文本'),
    sa.Column('origin_node_id', sa.BigInteger(), nullable=True, comment='匹配的起点节点ID，可空'),
    sa.Column('dest_node_id', sa.BigInteger(), nullable=True, comment='匹配的终点节点ID，可空'),
    sa.Column('origin_admin_code', sa.String(length=12), nullable=True, comment='起点城市行政区划代码'),
    sa.Column('origin_admin_name', sa.String(length=50), nullable=True, comment='起点城市名称（冗余）'),
    sa.Column('origin_location_type', sa.String(length=20), nullable=True, comment='NODE/CITY/WATERWAY/PORT/UNKNOWN'),
    sa.Column('dest_admin_code', sa.String(length=12), nullable=True, comment='终点城市行政区划代码'),
    sa.Column('dest_admin_name', sa.String(length=50), nullable=True, comment='终点城市名称（冗余）'),
    sa.Column('dest_location_type', sa.String(length=20), nullable=True, comment='NODE/CITY/WATERWAY/PORT/UNKNOWN'),
    sa.Column('commodity_id', sa.BigInteger(), nullable=True, comment='匹配的货品ID'),
    sa.Column('tonnage', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='解析的吨位'),
    sa.Column('loading_date', sa.Date(), nullable=True, comment='解析的装货日期'),
    sa.Column('freight_price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='解析的运价'),
    sa.Column('price_type', sa.SmallInteger(), nullable=True, comment='计价方式:1=按吨,2=按方,3=包干,4=按箱,5=面议'),
    sa.Column('contact_person', sa.String(length=64), nullable=True, comment='解析的联系人'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='解析的联系电话'),
    sa.Column('origin_confidence', sa.Integer(), nullable=True),
    sa.Column('dest_confidence', sa.Integer(), nullable=True),
    sa.Column('commodity_confidence', sa.Integer(), nullable=True),
    sa.Column('tonnage_confidence', sa.Integer(), nullable=True),
    sa.Column('overall_confidence', sa.Integer(), nullable=True),
    sa.Column('origin_candidates', sa.JSON(), nullable=True, comment='起点候选列表'),
    sa.Column('dest_candidates', sa.JSON(), nullable=True, comment='终点候选列表'),
    sa.Column('commodity_candidates', sa.JSON(), nullable=True, comment='货品候选列表'),
    sa.Column('ai_model', sa.String(length=64), nullable=True, comment='使用的AI模型'),
    sa.Column('ai_prompt_tokens', sa.Integer(), nullable=True, comment='消耗tokens'),
    sa.Column('parse_status', sa.String(length=32), nullable=True, comment='PENDING_CONFIRM/CONFIRMED/DISCARDED'),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True, comment='确认人ID'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='确认时间'),
    sa.Column('discard_reason', sa.String(length=256), nullable=True, comment='废弃原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity_standard.id'], ),
    sa.ForeignKeyConstraint(['dest_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['origin_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['raw_message_id'], ['cargo_raw_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commodity_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('alias_name', sa.String(length=128), nullable=False, comment='别名'),
    sa.Column('alias_type', sa.String(length=32), nullable=True, comment='COMMON/ABBR/DIALECT/INDUSTRY'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='匹配优先级'),
    sa.Column('match_keywords', sa.JSON(), nullable=True, comment='别名匹配关键词'),
    sa.Column('match_regex', sa.String(length=256), nullable=True, comment='别名匹配正则'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='MANUAL/AI/IMPORT'),
    sa.Column('confidence', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='别名置信度(0-100)'),
    sa.Column('is_ai_generated', sa.SmallInteger(), nullable=True, comment='是否AI建议别名'),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity_standard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_route_path_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False, comment='所属路线ID'),
    sa.Column('node_id', sa.BigInteger(), nullable=False, comment='途经节点ID'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='顺序（从1开始）'),
    sa.Column('distance_from_start', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='距路线起点距离(km)'),
    sa.Column('node_role', sa.String(length=32), nullable=True, comment='START/WAYPOINT/END'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['shipping_route_path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_route_path_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False, comment='所属路线ID'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='分段顺序'),
    sa.Column('segment_type', sa.String(length=32), nullable=False, comment='WATERWAY/RAILWAY/HIGHWAY/MULTIMODAL'),
    sa.Column('from_node_id', sa.BigInteger(), nullable=True),
    sa.Column('to_node_id', sa.BigInteger(), nullable=True),
    sa.Column('distance_km', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='分段里程(km)'),
    sa.Column('estimated_duration_hours', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='分段预计时长(小时)'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='分段说明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['shipping_route_path.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='anthropic / openai / deepseek / tongyi'),
    sa.Column('model', sa.String(length=64), nullable=False, comment='实际使用的模型 ID'),
    sa.Column('prompt_template_id', sa.BigInteger(), nullable=True, comment='关联的提示词模板'),
    sa.Column('prompt_version', sa.Integer(), nullable=True, comment='使用的提示词版本号'),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('raw_message_id', sa.BigInteger(), nullable=True),
    sa.Column('parse_result_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True, comment='本次解析整体置信度 0-100'),
    sa.Column('human_confirmed', sa.Boolean(), nullable=True, comment='True=无修改确认（AI对了），False=有修改确认（AI错了），NULL=未处理'),
    sa.Column('corrected_fields', sa.JSON(), nullable=True, comment='被人工修正的字段列表，如 ["origin_node","commodity"]'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parse_result_id'], ['cargo_ai_parse_result.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['ai_prompt_template.id'], ),
    sa.ForeignKeyConstraint(['raw_message_id'], ['cargo_raw_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_freight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freight_no', sa.String(length=32), nullable=False, comment='货源编号，格式 CS-YYYYMMDD-XXXXXXXX'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='TMS/WECHAT_AI/MANUAL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING/CONFIRMED/CANCELLED/EXPIRED'),
    sa.Column('record_source', sa.String(length=32), nullable=False, comment='记录来源：WECHAT_AI/TMS/MANUAL/IMPORT'),
    sa.Column('record_status', sa.String(length=32), nullable=False, comment='记录状态：ACTIVE/INVALID/ARCHIVED'),
    sa.Column('analysis_status', sa.String(length=32), nullable=False, comment='分析状态：READY/SKIPPED/INVALID'),
    sa.Column('data_quality_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='数据质量评分(0-100)'),
    sa.Column('location_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='位置匹配评分(0-100)'),
    sa.Column('commodity_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='货品匹配评分(0-100)'),
    sa.Column('is_test_data', sa.SmallInteger(), nullable=False, comment='1=测试数据'),
    sa.Column('is_long_term_info', sa.SmallInteger(), nullable=False, comment='1=长期有效信息'),
    sa.Column('source_message_time', sa.DateTime(), nullable=True, comment='来源消息时间'),
    sa.Column('origin_node_id', sa.BigInteger(), nullable=True, comment='装货节点ID，可空'),
    sa.Column('origin_admin_code', sa.String(length=12), nullable=True, comment='装货城市行政区划代码（统计主维度）'),
    sa.Column('origin_admin_name', sa.String(length=50), nullable=True, comment='装货城市名称（冗余）'),
    sa.Column('origin_region_id', sa.BigInteger(), nullable=True, comment='装货商业区域（系统自动推断）'),
    sa.Column('origin_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='装货地经度'),
    sa.Column('origin_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='装货地纬度'),
    sa.Column('origin_raw_text', sa.String(length=200), nullable=True, comment='装货地原始文本'),
    sa.Column('origin_precision', sa.String(length=12), nullable=False, comment='NODE/CITY/COORDINATE/UNKNOWN'),
    sa.Column('dest_node_id', sa.BigInteger(), nullable=True, comment='卸货节点ID，可空'),
    sa.Column('dest_admin_code', sa.String(length=12), nullable=True, comment='卸货城市行政区划代码（统计主维度）'),
    sa.Column('dest_admin_name', sa.String(length=50), nullable=True, comment='卸货城市名称（冗余）'),
    sa.Column('dest_region_id', sa.BigInteger(), nullable=True, comment='卸货商业区域（系统自动推断）'),
    sa.Column('dest_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='卸货地经度'),
    sa.Column('dest_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='卸货地纬度'),
    sa.Column('dest_raw_text', sa.String(length=200), nullable=True, comment='卸货地原始文本'),
    sa.Column('dest_precision', sa.String(length=12), nullable=False, comment='NODE/CITY/COORDINATE/UNKNOWN'),
    sa.Column('commodity_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity_text', sa.String(length=100), nullable=True, comment='原始货品描述'),
    sa.Column('tonnage', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='货物吨位(吨)'),
    sa.Column('volume', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='货物方数(m³)'),
    sa.Column('loading_date', sa.Date(), nullable=True, comment='装货日期'),
    sa.Column('expire_date', sa.Date(), nullable=True, comment='货源有效截止日'),
    sa.Column('freight_price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='运价'),
    sa.Column('price_type', sa.SmallInteger(), nullable=True, comment='1=按吨,2=按方,3=包干,4=按箱,5=面议'),
    sa.Column('price_unit', sa.String(length=32), nullable=True, comment='计价单位'),
    sa.Column('contact_person', sa.String(length=64), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('raw_message_id', sa.BigInteger(), nullable=True, comment='原始文本ID（WECHAT_AI渠道）'),
    sa.Column('parse_result_id', sa.BigInteger(), nullable=True, comment='AI解析结果ID（WECHAT_AI渠道）'),
    sa.Column('tms_external_id', sa.String(length=100), nullable=True, comment='TMS系统原始单号（TMS渠道）'),
    sa.Column('tms_raw_data', sa.JSON(), nullable=True, comment='TMS原始报文快照'),
    sa.Column('collector_id', sa.BigInteger(), nullable=True, comment='采集员/录入员ID'),
    sa.Column('audit_status', sa.SmallInteger(), nullable=False, comment='0=待审核,1=已通过,2=已驳回'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True, comment='提交人ID'),
    sa.Column('auditor_id', sa.BigInteger(), nullable=True, comment='审核人ID'),
    sa.Column('audited_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('audit_remark', sa.String(length=500), nullable=True, comment='审核意见'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity_standard.id'], ),
    sa.ForeignKeyConstraint(['dest_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['dest_region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['origin_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['origin_region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['parse_result_id'], ['cargo_ai_parse_result.id'], ),
    sa.ForeignKeyConstraint(['raw_message_id'], ['cargo_raw_message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freight_no'),
    sa.UniqueConstraint('tms_external_id')
    )
    with op.batch_alter_table('cargo_freight', schema=None) as batch_op:
        batch_op.create_index('ix_cargo_freight_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cargo_freight_dest_admin_code'), ['dest_admin_code'], unique=False)
        batch_op.create_index('ix_cargo_freight_dest_city', ['dest_admin_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cargo_freight_origin_admin_code'), ['origin_admin_code'], unique=False)
        batch_op.create_index('ix_cargo_freight_origin_city', ['origin_admin_code'], unique=False)
        batch_op.create_index('ix_cargo_freight_source', ['source_type'], unique=False)
        batch_op.create_index('ix_cargo_freight_status', ['status'], unique=False)

    op.create_table('tms_cargo_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tms_message_id', sa.String(length=100), nullable=False, comment='TMS侧唯一消息ID，防重复消费'),
    sa.Column('raw_payload', sa.JSON(), nullable=False, comment='TMS原始报文完整内容'),
    sa.Column('tms_origin_name', sa.String(length=200), nullable=True, comment='TMS装货地名称'),
    sa.Column('tms_origin_lng', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='TMS装货地经度'),
    sa.Column('tms_origin_lat', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='TMS装货地纬度'),
    sa.Column('tms_origin_region', sa.String(length=100), nullable=True, comment='TMS装货区域字段'),
    sa.Column('tms_dest_name', sa.String(length=200), nullable=True, comment='TMS卸货地名称'),
    sa.Column('tms_dest_lng', sa.DECIMAL(precision=11, scale=8), nullable=True, comment='TMS卸货地经度'),
    sa.Column('tms_dest_lat', sa.DECIMAL(precision=10, scale=8), nullable=True, comment='TMS卸货地纬度'),
    sa.Column('tms_dest_region', sa.String(length=100), nullable=True, comment='TMS卸货区域字段'),
    sa.Column('matched_origin_node_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_origin_admin_code', sa.String(length=12), nullable=True, comment='匹配的装货城市代码'),
    sa.Column('matched_dest_node_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_dest_admin_code', sa.String(length=12), nullable=True, comment='匹配的卸货城市代码'),
    sa.Column('match_strategy', sa.String(length=50), nullable=True, comment='NAME_EXACT/NAME_FUZZY/PROXIMITY/REGION/FALLBACK'),
    sa.Column('match_confidence', sa.SmallInteger(), nullable=True, comment='匹配置信度 0-100'),
    sa.Column('process_status', sa.String(length=20), nullable=True, comment='PENDING/MATCHED/IMPORTED/FAILED'),
    sa.Column('freight_id', sa.BigInteger(), nullable=True, comment='成功创建后关联的货源ID'),
    sa.Column('error_msg', sa.String(length=500), nullable=True, comment='失败原因'),
    sa.Column('consumed_at', sa.DateTime(), nullable=True, comment='消费时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['freight_id'], ['cargo_freight.id'], ),
    sa.ForeignKeyConstraint(['matched_dest_node_id'], ['transport_node.id'], ),
    sa.ForeignKeyConstraint(['matched_origin_node_id'], ['transport_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tms_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tms_cargo_raw')
    with op.batch_alter_table('cargo_freight', schema=None) as batch_op:
        batch_op.drop_index('ix_cargo_freight_status')
        batch_op.drop_index('ix_cargo_freight_source')
        batch_op.drop_index('ix_cargo_freight_origin_city')
        batch_op.drop_index(batch_op.f('ix_cargo_freight_origin_admin_code'))
        batch_op.drop_index('ix_cargo_freight_dest_city')
        batch_op.drop_index(batch_op.f('ix_cargo_freight_dest_admin_code'))
        batch_op.drop_index('ix_cargo_freight_created')

    op.drop_table('cargo_freight')
    op.drop_table('ai_call_log')
    op.drop_table('shipping_route_path_segment')
    op.drop_table('shipping_route_path_node')
    op.drop_table('commodity_alias')
    op.drop_table('cargo_ai_parse_result')
    op.drop_table('vessel_name_history')
    op.drop_table('vessel_dynamic')
    op.drop_table('vessel_ais_history')
    op.drop_table('shipping_route_path')
    with op.batch_alter_table('region_address_relation', schema=None) as batch_op:
        batch_op.drop_index('ix_region_address_node')

    op.drop_table('region_address_relation')
    op.drop_table('node_alias')
    op.drop_table('commodity_standard')
    op.drop_table('vessel')
    op.drop_table('transport_node')
    op.drop_table('sys_user_role')
    op.drop_table('shipping_route')
    with op.batch_alter_table('region_waterway_relation', schema=None) as batch_op:
        batch_op.drop_index('ix_region_waterway_region')

    op.drop_table('region_waterway_relation')
    with op.batch_alter_table('region_city_relation', schema=None) as batch_op:
        batch_op.drop_index('ix_region_city_region')

    op.drop_table('region_city_relation')
    op.drop_table('commodity_type')
    with op.batch_alter_table('cargo_commodity_stat_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_cargo_commodity_stat_date')
        batch_op.drop_index('ix_cargo_commodity_stat_cat')

    op.drop_table('cargo_commodity_stat_daily')
    op.drop_table('ai_prompt_version')
    op.drop_table('waterway')
    op.drop_table('vessel_type_dict')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    with op.batch_alter_table('ship_stat_region', schema=None) as batch_op:
        batch_op.drop_index('ix_ship_stat_region_id')

    op.drop_table('ship_stat_region')
    with op.batch_alter_table('ship_stat_dwt', schema=None) as batch_op:
        batch_op.drop_index('ix_ship_stat_dwt_label')

    op.drop_table('ship_stat_dwt')
    with op.batch_alter_table('ship_stat_city', schema=None) as batch_op:
        batch_op.drop_index('ix_ship_stat_city_code')

    op.drop_table('ship_stat_city')
    with op.batch_alter_table('ship_stat_age', schema=None) as batch_op:
        batch_op.drop_index('ix_ship_stat_age_label')

    op.drop_table('ship_stat_age')
    op.drop_table('region')
    op.drop_table('node_type')
    op.drop_table('commodity_category')
    with op.batch_alter_table('cargo_stat_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_cargo_stat_date')

    op.drop_table('cargo_stat_daily')
    op.drop_table('cargo_raw_message')
    with op.batch_alter_table('cargo_od_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_cargo_od_origin')
        batch_op.drop_index('ix_cargo_od_date')

    op.drop_table('cargo_od_daily')
    with op.batch_alter_table('cargo_city_heatmap', schema=None) as batch_op:
        batch_op.drop_index('ix_cargo_city_heatmap_date')
        batch_op.drop_index('ix_cargo_city_heatmap_city')

    op.drop_table('cargo_city_heatmap')
    with op.batch_alter_table('cargo_channel_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_cargo_channel_date')

    op.drop_table('cargo_channel_daily')
    with op.batch_alter_table('audit_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_task_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_task_target_id'))

    op.drop_table('audit_task')
    op.drop_table('audit_record')
    op.drop_table('ai_prompt_template')
    op.drop_table('admin_region')
    # ### end Alembic commands ###
