from __future__ import annotations

from pyproj import Geod


GEOD = Geod(ellps="WGS84")

ACTIVE_SEGMENT_STATUSES = {"CANDIDATE", "NEED_REPAIR", "CONFIRMED", "PUBLISH_BLOCKED", "PUBLISHED"}
SOURCE_CENTERLINE_TYPES = {"OSM_WATERWAY", "AIS_INFERRED", "MANUAL_IMPORT", "EXTERNAL_WATERWAY", "PUBLISHED"}

MIN_SEGMENT_LENGTH_M = 20.0
ENDPOINT_AUTO_SNAP_M = 30.0
ENDPOINT_WARN_M = 100.0
BOUNDARY_TOLERANCE_DEGREE = 0.0002
SHARP_TURN_DEGREE = 25.0
